imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: doctrine_extensions.yml }



framework:
    #esi:             ~
    translator:      { fallback: en }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:         ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    cache:            false

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    read_from:      %kernel.root_dir%/../web
    write_to:      %kernel.root_dir%/../web
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"
        less:
                    node: /usr/bin/node
                    node_paths: [/opt/lessc/lib, /usr/lib/node_modules]

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: "%kernel.root_dir%/data/data.db3"
        # path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true
services:
    my.listener:
        class: apb\appassBundle\EventListener\SearchIndexer
        tags:
            - { name: doctrine.event_listener, event: postPersist }
    #my.listener2:
     #   class: apb\appassBundle\EventListener\SearchIndexer2
      #  tags:
       #     - { name: doctrine.event_listener, event: postPersist, connection: default }
    my.subscriber:
        class: apb\appassBundle\EventListener\SearchIndexerSubscriber
        tags:
            - { name: doctrine.event_subscriber, connection: default }

 # Swiftmailer Configuration
swiftmailer:
    transport:  smtp
    #transport:  gmail
    host:       smtp.sendgrid.com
    #host:       smtp.gmail.com
    encryption: ssl

    spool:     { type: memory }

eo_passbook:
    wwdr_certificate:           %kernel.root_dir%/Resources/certificates/applewwdrca.pem
    output_path:                %kernel.root_dir%/logs/pkpass
    icon_file:                  %kernel.root_dir%/../../../../vendor/eo/passbook/tests/img/icon.png
parameters:
    uploads_directory: "/web/uploads"
    mopa_bootstrap.form.render_optional_text: false


jms_serializer:
    metadata:
        directories:
            FOSUB:
                namespace_prefix: "FOS\\UserBundle"
                path: "%kernel.root_dir%/serializer/FOSUserBundle"

fos_rest:
    routing_loader:
        default_format: json

fos_oauth_server:
    db_driver: orm       # Drivers available: orm, mongodb, or propel
    client_class:        apb\appassBundle\Entity\Client
    access_token_class:  apb\appassBundle\Entity\AccessToken
    refresh_token_class: apb\appassBundle\Entity\RefreshToken
    auth_code_class:     apb\appassBundle\Entity\AuthCode